config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new' #j'active la fonction new
	
  post '/login', to: 'sessions#create' #pour créer la session
	
  delete '/logout', to: 'sessions#destroy' #pour detruite, j'active la fonction delete
  get '/logout', to: 'sessions#destroy'

  root to: 'static_pages#home'

  get 'static_pages/secret_page', to: 'static_pages#secret_page'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  resources :users

  post   '/users/:id/edit(.:format)',   to: 'users#edit'

  get 'users/:id/users/destroy', to: 'users#destroy'
 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
                    
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }


  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	 user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      flash[:success] = 'Connected'
      redirect_to user
      
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
  	log_out
  	flash[:success] = 'sucessfully disconnected'
  	redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def secret_page

  	unless logged_in?
  		flash[:danger] = 'You must be connected to know about the secret !'
  		redirect_to login_path
  	end

  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)

  	if @user.save
      log_in @user
      flash[:success] = "Account created"
      redirect_to @user
    else 
      render 'new'
    end
  end

  def show
  	@user = User.find(params[:id])
  end

  def edit
  	@user = User.find(params[:id])
    unless logged_in? && @user == @current_user
      flash[:danger] = "You cannot modify someone else's account"
      redirect_to root_path
    end
  end

  def update
  	 @user = User.find(params[:id])

  	if @user.update(user_params)
    redirect_to user_path
  	else
    	render 'edit'
  	end
  end

  def destroy
  	@user = User.find(params[:id])
  	if @user.destroy
      redirect_to root_path
      flash[:success] = 'account deleted'
    end
  end

 private
  def user_params
  	params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in(user)
		session[:user_id] = user.id
	end

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	def logged_in?
		!current_user.nil?
	end

	def log_out
		session.delete(:user_id)
    @current_user = nil
	end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   '/' %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>

      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Secret</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

        <!-- Latest compiled and minified CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

		<!-- Optional theme -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

		<!-- Latest compiled and minified JavaScript -->
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  </head>

<%= render "layouts/header" %>
<div class="container">
    <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
  <body style="margin-top: 50px;"> 
  	
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3" align="center">

		<h1>Welcome!</h1>
		<p>Wanna know a bit about life the universe and everything ?</p>

		<br>
		<img src="http://cdn1-www.gamerevolution.com/assets/uploads/2016/08/file_12796_hitchhiker-guide.jpg" height= "150" width= "auto" />
		<br>


		<p>Please click on the link to <%= link_to "THE answer", 'static_pages/secret_page' %></p>

	</div>
</div>

app/views/static_pages/secret_page.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3" align="center">

		<h1>THE Answer</h1>
		

		<br>
		<iframe width="560" height="315" src="https://www.youtube.com/embed/aboZctrHfK8" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
		<br>


		
	</div>
</div>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<% provide(:title, "Update your profile") %>
<h1>Update your profile</h1>
<br>
<%= link_to 'Erase that account', 'users/destroy' %>
<br>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>

      <%= f.label :new_name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :new_email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :new_password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :new_password_confirmation %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>


      <br>
      <%= f.submit "Update", class: "btn btn-primary" %>
    <% end %>
   
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, "Sign Up") %>
<h1>Sign Up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:user, url: signup_path) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

       <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <br>
      <%= f.submit "Sign Up", class: "btn btn-primary" %>
    <% end %>
   
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">

  	<h1><%= @user.name %>'s profile</h1> 
  	<br>

		<p>email : <%= @user.email %></p>

		<br>
		<% if logged_in? && @user == @current_user %>
			<%= link_to 'Edit', edit_user_path(@user) %>
		<% end %>
	</div>
</div>